http:
  port: ${PORT:-9090}
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  users:
    host: '*'
    methods: 'GET, POST, PUT, DELETE'
    paths: '/users*'
  reservations:
    host: '*'
    methods: 'GET, POST, PUT, DELETE'
    paths: '/reservations*'
  hotels:
    host: '*'
    methods: 'GET, POST, PUT, DELETE'
    paths: '/hotels*'  
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  usersService:
    url: 'https://stayloop-users.onrender.com'
  reservationsService:
    url: 'https://stayloop-reservations.onrender.com'
  hotelsService:
    url: 'https://stayloop-hotels.onrender.com'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  users:
    apiEndpoints:
      - users
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: usersService 
              changeOrigin: true
  reservations:
    apiEndpoints:
      - reservations
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: reservationsService 
              changeOrigin: true
  hotels:
    apiEndpoints:
      - hotels
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: hotelsService 
              changeOrigin: true
